apiVersion: apps/v1
kind: Deployment
metadata:
  name: emqx
  namespace: uat
  labels:
    app: emqx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: emqx
  template:
    metadata:
      labels:
        app: emqx
    spec:
      containers:
      - name: emqx
        image: emqx/emqx:5.6.0
        ports:
        - containerPort: 1883   # MQTT TCP
        - containerPort: 8883   # MQTT SSL
        - containerPort: 8083   # MQTT WS
        - containerPort: 8084   # MQTT WSS
        - containerPort: 18083  # Dashboard
        env:
        - name: EMQX_DASHBOARD__DEFAULT_USER__PASSWORD
          value: "public" # đổi mật khẩu nếu muốn
---
apiVersion: v1
kind: Service
metadata:
  name: emqx-service
  namespace: uat
spec:
  selector:
    app: emqx
  type: NodePort # hoặc LoadBalancer nếu cần truy cập ngoài Internet
  ports:
    - name: mqtt
      protocol: TCP
      port: 1883
      targetPort: 1883
      nodePort: 31883
    - name: mqttssl
      protocol: TCP
      port: 8883
      targetPort: 8883
      nodePort: 31884
    - name: mqttws
      protocol: TCP
      port: 8083
      targetPort: 8083
      nodePort: 31885
    - name: mqttwss
      protocol: TCP
      port: 8084
      targetPort: 8084
      nodePort: 31886
    - name: dashboard
      protocol: TCP
      port: 18083
      targetPort: 18083
      nodePort: 31887