apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:26.2.0
        args: ["start-dev"]
        env:
        # - name: KC_HOSTNAME
        #   value: keycloak.tieuhocdong.online
        - name: QUARKUS_TRANSACTION_MANAGER_ENABLE_RECOVERY
          value: "true"
        - name: KC_TRANSACTION_XA_ENABLED
          value: "true"
        - name: KC_DB
          value: mysql
        - name: KC_DB_URL_HOST
          value: mysql-service
        - name: KC_DB_URL_DATABASE
          value: keycloak
        - name: KC_DB_USERNAME
          value: root
        - name: KC_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: KC_DB_URL_PORT
          value: "3306"
        - name: KC_DB_URL_PROPERTIES
          value: "?useSSL=false&allowPublicKeyRetrieval=true"
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KEYCLOAK_ADMIN
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: KEYCLOAK_ADMIN
        - name: KEYCLOAK_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: KEYCLOAK_ADMIN_PASSWORD
        ports:
        - containerPort: 8080
        - containerPort: 8443
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1"