apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: uat
  labels:
    app: keycloak
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
    - port: 443
      targetPort: 8443
      name: https
      nodePort: 30443
  selector:
    app: keycloak