apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  namespace: uat
  labels:
    app: zookeeper
spec:
  type: NodePort
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
